# Generated by Django 4.2 on 2024-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_email",
            field=models.EmailField(
                blank=True,
                help_text="Для подтверждения изменения необходимо пройти по ссылке, направленной на email",
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
    ]
