# Generated by Django 5.0.4 on 2024-05-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="Post",
        ),
    ]
